# Start with a base image containing Java runtime
leegreiner/oracleclient-openjdk17:latest

# Add Maintainer Info
LABEL maintainer="lee.greiner@duke.edu"

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 8443 available to the world outside this container
EXPOSE 8443

# The application's jar file
ARG JAR_FILE

# Add the application's jar to the container
ADD ${JAR_FILE} /app/baseProject.jar

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

USER appuser

# Run the jar file 
ENTRYPOINT ["java", "-jar", "/app/baseProject.jar"]