INSERT INTO PRIVILEGE (PRIVILEGE_ID, ALTERNATE_ID, CREATED_DATE, LAST_MODIFIED_DATE, VERSION, NAME) VALUES (privilege_seq.nextval, '42D42A6CE4A34B44A214F0ED9C43AF79', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'View Users');
INSERT INTO PRIVILEGE (PRIVILEGE_ID, ALTERNATE_ID, CREATED_DATE, LAST_MODIFIED_DATE, VERSION, NAME) VALUES (privilege_seq.nextval, 'D632420D186843F3BCD3E536D59E979B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'Edit Users');

INSERT INTO ROLE (ROLE_ID, ALTERNATE_ID, CREATED_DATE, LAST_MODIFIED_DATE, VERSION, NAME) VALUES (role_seq.nextval, '7D716E408FEB4D47A2A1ED17683B60F6', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'User');
INSERT INTO ROLE (ROLE_ID, ALTERNATE_ID, CREATED_DATE, LAST_MODIFIED_DATE, VERSION, NAME) VALUES (role_seq.nextval, 'EEF71F27DBE143268A8F9B7E9561755E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'Administrator');

INSERT INTO ROLES_TO_PRIVILEGES (ROLE_FK, PRIVILEGE_FK) VALUES (role_seq.currval - 1, privilege_seq.currval - 1);
INSERT INTO ROLES_TO_PRIVILEGES (ROLE_FK, PRIVILEGE_FK) VALUES (role_seq.currval, privilege_seq.currval - 1);
INSERT INTO ROLES_TO_PRIVILEGES (ROLE_FK, PRIVILEGE_FK) VALUES (role_seq.currval, privilege_seq.currval);