spring:
  application:    name: "@project.name@"

  datasource:
    continue-on-error: true
    initialization-mode: never
    platform: oracle
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    username: baseapp
    password: 'tta&cno2'
    hikari:      auto-commit: false
      connection-test-query: select 1 from dual
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 8
      minimum-idle: 0
      initialization-fail-timeout: -1
      pool-name: baseapphikaripool
    
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: true # needed for audit history
    properties:      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        javax:
          cache:
            missing_cache_strategy: create-warn
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            uri: classpath:ehcache.xml
        connection:
          provider_disables_autocommit: true
        dialect: org.hibernate.dialect.Oracle12cDialect
        default_schema: baseapp
#        jdbc:
#          lob:
            # Fix Postgres JPA Error (Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented).
#            non_contextual_creation: true
        show_sql: false
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      org:
        hibernate:
          envers:
            track_entities_changed_in_revision: true
  
  liquibase:
    change-log: classpath:/liquibase/changelog/changelog-master.xml
    tag: "@project.version@"
              
  mail:
    default-encoding: UTF-8
    host: smtpgw.duhs.duke.edu
  
  main:
    banner-mode: 'off'
    
  mvc:
    hiddenmethod:
      filter:
        enabled: true
        
  quartz:    job-store-type: jdbc
    overwrite-existing-jobs: true
    scheduler-name: baseProjectScheduler
    startup-delay: 20
    properties:      org:
        quartz:
          jobStore:
            clusterCheckinInterval: 20000
            driverDelegateClass: org.quartz.impl.jdbcjobstore.oracle.OracleDelegate
            isClustered: true
          scheduler:
            instanceId: AUTO
         
  messages:    basename: i18n/messages
    
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 8h
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
             
server:  compression:    enabled: true
  error:
    whitelabel:
      enabled: false
  port: 8080
  ssl:
    ciphers: TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    enabled-protocols: TLSv1.2,TLSv1.3
    enabled: false
    key-store: classpath:keystore.p12
#   encrypt_key abc123    
    key-store-password: '{cipher}f04a152e702ddaa5039a13cfa98fc11437803467e704a72d9edd7a7eb24b09f3'
    key-store-type: PKCS12
    key-alias: tomcat
    protocol: TLS
  tomcat:
    basedir: /opt/apps/baseProject    accesslog:
      directory: logs      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %{X-Forwarded-For}i "%{Referer}i" "%{User-Agent}i"'
      request-attributes-enabled: true
      rotate: true
      suffix: .log
    mbeanregistry:
      enabled : true
    
management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    
info:
  app:
    name: "@project.name@"
    description: Base Project description
    version: "@project.version@"
    
logging:  level:    edu.duke.rs: debug
    liquibse: info
#    org.apache.http.wire: debug
    
app:
  datasource:
    startupValidationInterval: 5
    startupValidationTimeout: 60
  defaultEmailFrom: abc@123.com
  google:
    analysicsTrackingId: None
  jobs:
#   daily at 3AM
    disableUnusedAccountsCronSchedule: '0 0 3 ? * * *'
#   hourly on the hour
    expirePasswordChangeIdsCronSchedule: '0 0 * ? * * *'
  hazelcast:
    instanceName: baseProject-hazelcast-instance
    multicastPort: 5702
    bruteForceTtlSeconds: 86400
    bruteForceSize: 10000
  kubernetes:
    hazelcastDiscoveryService: baseProject-hazelcast-service
    namespace: baseProject
  management:
    userName: mgmt_user
# changeMe1
    password: '{cipher}8595c9f67620ea4ed95370dca6c87ad9317f8bc4b035e9971b71d47a1632bd73'
  security:
    disableUnusedAccountsGreaterThanMonths: 12
    maxBruteForceAttempts: 5
    numberOfLoginAttemptFailuresBeforeTemporaryLock: 3
    temporaryLockSeconds: 300
    password:
      minLength: 8
      maxLength: 16
      numberLowerCase: 1
      numberUpperCase: 1
      numberDigits: 1
      numberSpecial: 0
      expirationDays: 90
      resetPasswordExpirationDays: 2
      historySize: 10
      
---
spring:
  config:
    activate:
      on-profile:
      - samlSecurity   
  
saml:
  sso:
    default-success-url: /home
    default-failure-url: /error?error=404
    idp-selection-page-url: /idpselection
    idp:
      metadata-location: classpath:/security/idp-duke.xml
    logout:
      default-target-url: https://shib.oit.duke.edu/cgi-bin/logout.pl?returnto=http://www.yahoo.com
    metadata-generator:
      entity-id: https://wearables-local.dcri.duke.edu
    metadata-manager:
      refresh-check-interval: 0
    extended-metadata:
      idp-discovery-enabled: false
    key-manager:
      private-key-der-location: classpath:/security/private-local.der
      public-key-pem-location: classpath:/security/public-local.cert
  
---
spring:   
  config:
    activate:      on-profile:      - local   
     
  jpa:    show-sql: true
    hibernate:      ddl-auto: create-drop
    open-in-view: false # needed for audit history
    properties:      hibernate:
        format_sql: true
        generate_statistics: true
        show_sql: true
        
  mail:
    default-encoding: UTF-8
    host: localhost
    port: 1025
    
  web:
    resources:      cache:        cachecontrol:          no-cache: true
    
logging:
  level:
#    org.hibernate.type.descriptor.sql: trace
#    com.hazelcast: debug
    edu.duke.drc.baseProject: debug
    org.springframework.cache: trace
    org.hibernate.stat: debug
#    org.springframework.cache: trace
#    org.springframework.security: debug
#    org.springframework.web.servlet.mvc.method.annotation: trace
    
app:
  google:
    analysicsTrackingId: UA-143586895-1
  url: 'https://localhost:8443'
  
---

spring:
  config:
    activate:
      on-profile:
      - test   
    
  datasource:
    platform: h2
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema:
        javax:
          cache:
            uri: ehcache.xml
        
  mail:
    host: localhost
    port: 9999
    
logging:
  level:
    root: off
    edu.duke.rs: off
    org.springframework: off
    
server:
  ssl:
    enabled: false   
    key-store-password:
    
app:
  google:
    analysicsTrackingId: None
  management:
    userName: mgmt_user
    password: changeMe1
  passwordExpirationDays: 90
  resetPasswordExpirationDays: 2
  url: https://localhost
    