info:
  app:
    name: "@project.name@"
    description: Base Project description
    version: "@project.version@"

logging:
  level:
    edu.duke.rs.baseProject: info
    liquibse: info
#    org.apache.http.wire: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    
server:
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false
  port: 8080
  ssl:
    ciphers: TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    enabled-protocols: TLSv1.2,TLSv1.3
    enabled: false
    key-store: classpath:keystore.p12
#   encrypt_key abc123    
    key-store-password: '{cipher}f04a152e702ddaa5039a13cfa98fc11437803467e704a72d9edd7a7eb24b09f3'
    key-store-type: PKCS12
    key-alias: tomcat
    protocol: TLS
  tomcat:
    basedir: /opt/apps/baseProject
    accesslog:
      directory: logs
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %{X-Forwarded-For}i "%{Referer}i" "%{User-Agent}i"'
      request-attributes-enabled: true
      rotate: true
      suffix: .log
    mbeanregistry:
      enabled : true

spring:
  application:
    name: "@project.name@"
      
  cloud:
    config:
      enabled: 'false'
    discovery:
      client:
        composite-indicator:
          enabled: 'false'
          
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    username: baseapp
    password: '{cipher}13f656d075e684af047cf04b19305c4bacc89da868a78565b850dd19f7d526ed'
    hikari:
      auto-commit: false
      connection-test-query: select 1 from dual
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20
      initialization-fail-timeout: -1
      pool-name: baseapphikaripool
    
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true # needed for audit history
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          envers store_data_at_delete: true
        connection:
          provider_disables_autocommit: true
        default_schema: baseapp
        dialect: org.hibernate.dialect.Oracle12cDialect
        javax:
          cache:
            missing_cache_strategy: create-warn
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            uri: classpath:ehcache.xml
        jdbc:
          batch_size: 15
          batch_versioned_data: true
          fetch_size: 50
          order_inserts: true
          order_updates: true
          time_zone: UTC
#          lob:
            # Fix Postgres JPA Error (Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented).
#            non_contextual_creation: true
        query:
          in_clause_parameter_padding: true
        generate_statistics: false
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      org:
        hibernate:
          envers:
            store_data_at_delete: true
            track_entities_changed_in_revision: true
  
  liquibase:
    change-log: classpath:/liquibase/changelog/changelog-master.xml
    tag: "@project.version@"
              
  mail:
    default-encoding: UTF-8
    host: smtpgw.duhs.duke.edu
  
  main:
    banner-mode: 'off'
  
  messages:
    basename: i18n/messages
     
  mvc:
    hiddenmethod:
      filter:
        enabled: true
        
  quartz:
    job-store-type: jdbc
    overwrite-existing-jobs: true
    scheduler-name: baseProjectScheduler
    startup-delay: 20
    properties:
      org:
        quartz:
          jobStore:
            clusterCheckinInterval: 20000
            driverDelegateClass: org.quartz.impl.jdbcjobstore.oracle.OracleDelegate
            isClustered: true
          scheduler:
            instanceId: AUTO
          threadPool:
            threadCount: 5
  
  sql: 
    init:
      continue-on-error: true
      enabled: false
      platform: oracle
       
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 8h
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
 
app:
  datasource:
    startupValidationInterval: 5
    startupValidationTimeout: 60
  defaultEmailFrom: abc@123.com
  google:
    analysicsTrackingId: None
  jobs:
#   daily at 3AM
    disableUnusedAccountsCronSchedule: '0 0 3 ? * * *'
#   hourly on the hour
    expirePasswordChangeIdsCronSchedule: '0 0 * ? * * *'
  hazelcast:
    instanceName: baseProject-hazelcast-instance
    multicastPort: 5702
    bruteForceTtlSeconds: 86400
    bruteForceSize: 10000
  kubernetes:
    hazelcastDiscoveryService: baseProject-hazelcast-service
    namespace: baseProject
  management:
    userName: mgmt_user
# changeMe1
    password: '{cipher}8595c9f67620ea4ed95370dca6c87ad9317f8bc4b035e9971b71d47a1632bd73'
  security:
    disableUnusedAccountsGreaterThanMonths: 12
    maxBruteForceAttempts: 5
    numberOfLoginAttemptFailuresBeforeTemporaryLock: 3
    temporaryLockSeconds: 300
    password:
      minLength: 8
      maxLength: 16
      numberLowerCase: 1
      numberUpperCase: 1
      numberDigits: 1
      numberSpecial: 0
      expirationDays: 90
      resetPasswordExpirationDays: 2
      historySize: 10

javamelody:
  # Initialization parameters for JavaMelody
  # See: https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
  init-parameters:
    disabled: false
    log: false
    url-exclude-pattern: (/css/.*|/js/.*|/img/.*|/webfonts/.*|/i18n/.*|/webjars/.*)
    warning-threshold-millis: 1000
    severe-threshold-millis: 2000

decorator:
  datasource:
    enabled: false
          
---
spring:
  config:
    activate:
      on-profile:
      - samlSecurity   
  
saml:
  keystore:
    location: classpath:saml/samlKeystore.jks
    password: '{cipher}ec8a0cc266ceb9c74273d2bbe6562840bcd9aca45bf9924cc61f45e2007245a1'
    alias: duke
  idp: https://shib.oit.duke.edu/shibboleth-idp
  sp: http://samltest.drc.duke.edu
# needed for Duke SAML logout
  logoutRedirectUrl: https://shib.oit.duke.edu/cgi-bin/logout.pl?logoutWithoutPrompt=1&returnto=http://www.duke.edu
  
---

logging:
  level:
#    org.hibernate.type.descriptor.sql: trace
#    com.hazelcast: debug
    edu.duke.rs.baseProject: debug
    net.ttddyy.dsproxy: debug
#    org.hibernate.cache: debug
#    org.hibernate.SQL: debug
#    org.hibernate.stat: debug
#    org.springframework.cache: trace
#    org.springframework.cache: trace
#    org.springframework.security: debug
#    org.springframework.web.servlet.mvc.method.annotation: trace
spring:
  config:
    activate:
      on-profile:
      - local   

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false # for dev only to prevent unknown queries when pages rendered
    properties:
      hibernate:
        format_sql: true
#        generate_statistics: true
        hbm2ddl:
          import_files: dbdata/importSchemaChanges.sql,dbdata/importRolesPrivileges.sql,dbdata/importUsers.sql
        session:
          events:
            log:
#              LOG_QUERIES_SLOWER_THAN_MS: 2000
  mail:
    default-encoding: UTF-8
    host: localhost
    port: 1025
    
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true   
    
app:
  google:
    analysicsTrackingId: UA-143586895-1
  url: 'https://localhost:8080'

decorator:
  datasource:
    enabled: true
    datasource-proxy:
      multiline: true
      query:
        enable-logging: true
        log-level: debug
      slow-query:
        enable-logging: true
        log-level: warn
        threshold: 3
---

spring:
  autoconfigure:
    exclude: net.bull.javamelody.JavaMelodyAutoConfiguration
    
  config:
    activate:
      on-profile:
      - test
        
  quartz:
    jdbc:
      # let liquibase initialize quartz tables
      initialize-schema: never
    
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema:
        javax:
          cache:
            uri: ehcache.xml
        
  mail:
    host: localhost
    port: 9999
    
  sql: 
    init:
      platform: h2

logging:
  level:
    root: off
    edu.duke.rs.baseProject: off
#    org.springframework: debug
    
server:
  ssl:
    enabled: false   
    key-store-password:
    
app:
  google:
    analysicsTrackingId: None
  management:
    userName: mgmt_user
    password: changeMe1
  passwordExpirationDays: 90
  resetPasswordExpirationDays: 2
  url: https://localhost
    