spring:
  application:    name: @project.name@
  boot:    admin:      client:        url: https://localhost:8449
        username: 'admin'
#       changeMe1
        password: '{cipher}8595c9f67620ea4ed95370dca6c87ad9317f8bc4b035e9971b71d47a1632bd73'
        
        instance:          metadata:
            user.name: mgmt_user
#           changeMe1
            user.password: '{cipher}8595c9f67620ea4ed95370dca6c87ad9317f8bc4b035e9971b71d47a1632bd73'

  datasource:
    initialization-mode: never
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/devdb?currentSchema=baseapp
    username: lmg
    password: 'tta&cno2'
    hikari:      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1200000
      maximum-pool-size: 20
      minimum-idle: 5
      
  jpa:
    jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:      hibernate:
        connection:
          provider_disables_autocommit: true
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        default_schema: baseapp
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: false
      org:
        hibernate:
          envers:
            track_entities_changed_in_revision: true
            global_with_modified_flag: true
            
  mail:
    default-encoding: UTF-8
    host: smtpgw.duhs.duke.edu
    
  quartz:    job-store-type: jdbc
    overwrite-existing-jobs: true
    jdbc:      initialize-schema: always
    scheduler-name: baseProjectScheduler
    startup-delay: 20
    properties:      org:
        quartz:
          jobStore:
            clusterCheckinInterval: 20000
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: true
          scheduler:
            instanceID: AUTO
    
  main:
    banner-mode: 'off'
  resources:
    cache:
      cachecontrol:
        max-age: 3600    
         
  messages:    basename: i18n/messages
  session:    store-type: jdbc
    timeout: 1h
             
server:  compression:    enabled: true
  error:
    whitelabel:
      enabled: false
  port: 8443
  servlet:    session:      timeout: 60m
  ssl:
    ciphers: TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    enabled-protocols: TLSv1.2
    enabled: true
    key-store: classpath:keystore.p12
#   encrypt_key abc123    
    key-store-password: '{cipher}f04a152e702ddaa5039a13cfa98fc11437803467e704a72d9edd7a7eb24b09f3'
    key-store-type: PKCS12
    key-alias: tomcat
    protocol: TLS
  tomcat:
    basedir: /opt/apps/baseProject    accesslog:
      directory: logs      enabled: true
      request-attributes-enabled: true
      rotate: true
      suffix: .log
    
management:
  endpoints:    web:      exposure:        include: '*'
  endpoint:
    health:
      show-details: always
    
info:
  app:
    name: @project.name@
    description: Base Project description
    version: @project.version@
    
logging:  level:    edu.duke.rs: info
#    org.apache.http.wire: debug
    
app:
  defaultEmailFrom: abc@123.com
  google:
    analysicsTrackingId: None	
  management:
    userName: mgmt_user
# changeMe1
    password: '{cipher}8595c9f67620ea4ed95370dca6c87ad9317f8bc4b035e9971b71d47a1632bd73'
  passwordExpirationDays: 90
  resetPasswordExpirationDays: 2
  security:
    password:
      minLength: 8
      maxLength: 16
      numberLowerCase: 1
      numberUpperCase: 1
      numberDigits: 1
      numberSpecial: 0
      
---
spring:
  profiles: samlSecurity
  
saml:
  sso:
    metadata-generator:
      entity-id: https://wearables-local.dcri.duke.edu
    logout:
      default-target-url: https://shib.oit.duke.edu/cgi-bin/logout.pl?returnto=http://www.yahoo.com
    key-manager:
      private-key-der-location: classpath:/security/private-local.der
      public-key-pem-location: classpath:/security/public-local.cert
  
---
spring:  profiles: local
  resources:    cache:      cachecontrol:        no-cache: true
  jpa:    show-sql: true
    hibernate:      ddl-auto: create-drop
    properties:      hibernate:
        format_sql: true
        show_sql: true
    
logging:
  level:
    edu.duke.rs: debug
#    org.springframework.security: debug
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
    
app:
  google:
    analysicsTrackingId: UA-143586895-1
  url: 'https://localhost:8443'
    
---

spring:
  profiles: test
  autoconfigure.exclude: org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
  boot:
    admin:
      client:
        enabled: false
        password: 
        instance:
          metadata:
            user.password: 
  datasource:
    platform: h2
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema:
        
  mail:    host: localhost
    
logging:
  level:
    root: off
    edu.duke.rs: off
    org.springframework: off
    
server:
  port:
  ssl:
    enabled: false   
    key-store-password:
    
app:
  google:
    analysicsTrackingId: None
  management:
    userName: mgmt_user
    password: changeMe1
  passwordExpirationDays: 90
  resetPasswordExpirationDays: 2
  url: https://localhost