spring:
  main:
    banner-mode: 'off'
  resources:
    cache:
      cachecontrol:
        max-age: 3600
      
server:  compression:    enabled: true
    
---
spring:  profiles: local
  resources:    cache:      cachecontrol:        no-cache: true