spring:
  application:    name: @project.name@
  datasource:
    initialization-mode: never
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/devdb?currentSchema=baseapp
    username: lmg
    password: 'tta&cno2'
  jpa:
    jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        default_schema: baseapp
        jdbc:
          lob:
            non_contextual_creation: true
  quartz:    job-store-type: jdbc
    overwrite-existing-jobs: true
    scheduler-name: baseProjectScheduler
    startup-delay: 20
    properties:      org:
        quartz:
          jobStore:
            clusterCheckinInterval: 20000
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: true
          scheduler:
            instanceID: AUTO
    
  main:
    banner-mode: 'off'
  resources:
    cache:
      cachecontrol:
        max-age: 3600    
         
  messages:    basename: i18n/messages
  session:    store-type: jdbc
             
server:  compression:    enabled: true
  error:
    whitelabel:
      enabled: false
  port: 8443
  servlet:    session:      timeout: 60m
  ssl:
    ciphers: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA
    enabled-protocols: TLSv1.2
    enabled: true
    key-store: classpath:keystore.p12
#   encrypt_key abc123    
    key-store-password: '{cipher}f04a152e702ddaa5039a13cfa98fc11437803467e704a72d9edd7a7eb24b09f3'
    key-store-type: PKCS12
    key-alias: tomcat
    protocol: TLS
  tomcat:
    basedir: /opt/apps/baseProject    accesslog:
      directory: logs      enabled: true
      request-attributes-enabled: true
      rotate: true
      suffix: .log
    
management:
  endpoints:    web:      exposure:        include: '*'
    
info:
  app:
    name: @project.name@
    description: Base Project description
    version: @project.version@
    
logging:  level:    edu.duke.rs: info
    
app:
  google:
    analysicsTrackingId: None	
  management:
    userName: mgmt_user
# changeMe1
    password: '{cipher}8595c9f67620ea4ed95370dca6c87ad9317f8bc4b035e9971b71d47a1632bd73'
    
---
spring:  profiles: local
  resources:    cache:      cachecontrol:        no-cache: true
  jpa:    show-sql: true
    hibernate:      ddl-auto: create-drop
    properties:      hibernate:
        format_sql: true
    
logging:
  level:
    edu.duke.rs: debug
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
    
app:
  google:
    analysicsTrackingId: UA-143586895-1
    
---

spring:
  profiles: test
  autoconfigure.exclude: org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
  datasource:
    platform: h2
    url: jdbc:h2:mem:test
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema:
    
logging:
  level:
    edu.duke.rs: info
    
server:
  port:
  ssl:
    enabled: false   
    key-store-password:
    
app:
  management:
    userName: mgmt_user
    password: changeMe1
  google:
    analysicsTrackingId: None