INSERT INTO PRIVILEGE (ALTERNATE_ID, CREATED_DATE, LAST_MODIFIED_DATE, VERSION, NAME) VALUES ('42D42A6CE4A34B44A214F0ED9C43AF79', SYSDATE, SYSDATE, 0, 'View Users');
INSERT INTO AUDIT_REVISION_ENTITY (timestamp, initiator, user_id, id) select trunc(extract(day from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*86400+extract(hour from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*3600+extract(minute from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*60+extract(second from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00')))*1000, 'System', null, audit_revision_entity_seq.nextval from dual;
INSERT INTO PRIVILEGE_AUD (PRIVILEGE_ID, ALTERNATE_ID, CREATED_DATE, LAST_MODIFIED_DATE, NAME, REV, REVTYPE) VALUES ((select privilege_id from privilege where name = 'View Users'), '42D42A6CE4A34B44A214F0ED9C43AF79', SYSDATE, SYSDATE, 'View Users', audit_revision_entity_seq.currval, 0);
INSERT INTO REVCHANGES (rev, entityname) values (audit_revision_entity_seq.currval, 'edu.duke.rs.baseProject.role.Privilege');

INSERT INTO PRIVILEGE (ALTERNATE_ID, CREATED_DATE, LAST_MODIFIED_DATE, VERSION, NAME) VALUES ('D632420D186843F3BCD3E536D59E979B', SYSDATE, SYSDATE, 0, 'Edit Users');
INSERT INTO AUDIT_REVISION_ENTITY (timestamp, initiator, user_id, id) select trunc(extract(day from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*86400+extract(hour from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*3600+extract(minute from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*60+extract(second from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00')))*1000, 'System', null, audit_revision_entity_seq.nextval from dual;
INSERT INTO PRIVILEGE_AUD (PRIVILEGE_ID, ALTERNATE_ID, CREATED_DATE, LAST_MODIFIED_DATE, NAME, REV, REVTYPE) VALUES ((select privilege_id from privilege where name = 'Edit Users'), 'D632420D186843F3BCD3E536D59E979B', SYSDATE, SYSDATE, 'Edit Users', audit_revision_entity_seq.currval, 0);
INSERT INTO REVCHANGES (rev, entityname) values (audit_revision_entity_seq.currval, 'edu.duke.rs.baseProject.role.Privilege');

INSERT INTO ROLE (ALTERNATE_ID, CREATED_DATE, LAST_MODIFIED_DATE, VERSION, NAME) VALUES ('7D716E408FEB4D47A2A1ED17683B60F6', SYSDATE, SYSDATE, 0, 'User');
INSERT INTO AUDIT_REVISION_ENTITY (timestamp, initiator, user_id, id) select trunc(extract(day from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*86400+extract(hour from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*3600+extract(minute from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*60+extract(second from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00')))*1000, 'System', null, audit_revision_entity_seq.nextval from dual;
INSERT INTO ROLE_AUD (ROLE_ID, ALTERNATE_ID, CREATED_DATE, LAST_MODIFIED_DATE, NAME, REV, REVTYPE) VALUES ((select role_id from role where name = 'User'), '7D716E408FEB4D47A2A1ED17683B60F6', SYSDATE, SYSDATE, 'User', audit_revision_entity_seq.currval, 0);
INSERT INTO REVCHANGES (rev, entityname) values (audit_revision_entity_seq.currval, 'edu.duke.rs.baseProject.role.Role');

INSERT INTO ROLE (ALTERNATE_ID, CREATED_DATE, LAST_MODIFIED_DATE, VERSION, NAME) VALUES ('EEF71F27DBE143268A8F9B7E9561755E', SYSDATE, SYSDATE, 0, 'Administrator');
INSERT INTO AUDIT_REVISION_ENTITY (timestamp, initiator, user_id, id) select trunc(extract(day from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*86400+extract(hour from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*3600+extract(minute from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*60+extract(second from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00')))*1000, 'System', null, audit_revision_entity_seq.nextval from dual;
INSERT INTO ROLE_AUD (ROLE_ID, ALTERNATE_ID, CREATED_DATE, LAST_MODIFIED_DATE, NAME, REV, REVTYPE) VALUES ((select role_id from role where name = 'Administrator'), 'EEF71F27DBE143268A8F9B7E9561755E', SYSDATE, SYSDATE, 'Administrator', audit_revision_entity_seq.currval, 0);
INSERT INTO REVCHANGES (rev, entityname) values (audit_revision_entity_seq.currval, 'edu.duke.rs.baseProject.role.Role');

INSERT INTO ROLES_TO_PRIVILEGES (ROLE_FK, PRIVILEGE_FK) VALUES ((select role_id from role where name = 'User'), (select privilege_id from privilege where name = 'View Users'));
INSERT INTO AUDIT_REVISION_ENTITY (timestamp, initiator, user_id, id) select trunc(extract(day from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*86400+extract(hour from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*3600+extract(minute from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*60+extract(second from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00')))*1000, 'System', null, audit_revision_entity_seq.nextval from dual;
INSERT INTO ROLES_TO_PRIVILEGES_AUD (REV, REVTYPE, ROLE_FK, PRIVILEGE_FK) VALUES (audit_revision_entity_seq.currval, 0, (select role_id from role where name = 'User'), (select privilege_id from privilege where name = 'View Users'));
INSERT INTO REVCHANGES (rev, entityname) values (audit_revision_entity_seq.currval, 'edu.duke.rs.baseProject.role.Role');
INSERT INTO REVCHANGES (rev, entityname) values (audit_revision_entity_seq.currval, 'edu.duke.rs.baseProject.role.Privilege');

INSERT INTO ROLES_TO_PRIVILEGES (ROLE_FK, PRIVILEGE_FK) VALUES ((select role_id from role where name = 'Administrator'), (select privilege_id from privilege where name = 'View Users'));
INSERT INTO AUDIT_REVISION_ENTITY (timestamp, initiator, user_id, id) select trunc(extract(day from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*86400+extract(hour from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*3600+extract(minute from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*60+extract(second from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00')))*1000, 'System', null, audit_revision_entity_seq.nextval from dual;
INSERT INTO ROLES_TO_PRIVILEGES_AUD (REV, REVTYPE, ROLE_FK, PRIVILEGE_FK) VALUES (audit_revision_entity_seq.currval, 0, (select role_id from role where name = 'Administrator'), (select privilege_id from privilege where name = 'View Users'));
INSERT INTO REVCHANGES (rev, entityname) values (audit_revision_entity_seq.currval, 'edu.duke.rs.baseProject.role.Role');
INSERT INTO REVCHANGES (rev, entityname) values (audit_revision_entity_seq.currval, 'edu.duke.rs.baseProject.role.Privilege');

INSERT INTO ROLES_TO_PRIVILEGES (ROLE_FK, PRIVILEGE_FK) VALUES ((select role_id from role where name = 'Administrator'), (select privilege_id from privilege where name = 'Edit Users'));
INSERT INTO AUDIT_REVISION_ENTITY (timestamp, initiator, user_id, id) select trunc(extract(day from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*86400+extract(hour from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*3600+extract(minute from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00'))*60+extract(second from (SYS_EXTRACT_UTC(systimestamp)-timestamp '1970-01-01 00:00:00 +00:00')))*1000, 'System', null, audit_revision_entity_seq.nextval from dual;
INSERT INTO ROLES_TO_PRIVILEGES_AUD (REV, REVTYPE, ROLE_FK, PRIVILEGE_FK) VALUES (audit_revision_entity_seq.currval, 0, (select role_id from role where name = 'Administrator'), (select privilege_id from privilege where name = 'Edit Users'));
INSERT INTO REVCHANGES (rev, entityname) values (audit_revision_entity_seq.currval, 'edu.duke.rs.baseProject.role.Role');
INSERT INTO REVCHANGES (rev, entityname) values (audit_revision_entity_seq.currval, 'edu.duke.rs.baseProject.role.Privilege');